name: CI for HTML Project

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Validar estructura del proyecto
        run: |
          echo "Archivos presentes:"
          ls -R
          echo "Proyecto HTML verificado correctamente ✅"
